---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-microk8s-controller
spec:
  selector:
    matchLabels:
      name: nginx-ingress-microk8s
  template:
    metadata:
      labels:
        name: nginx-ingress-microk8s
    spec:
      containers:
      - name: nginx-ingress-microk8s
        ports:
        - containerPort: 6379
          hostPort: 6379
          protocol: TCP
